#!/bin/bash
INSTLOG="install.log"

# Install stage: archinstall; audio - pipewire; packages git,vim; optional repo - multilib
# nmcli device wifi connect SDT CHANGE_ME_WIFI_NAME password CHANGE_ME_PASSWORD
# cd
# git clone https://github.com/KoKud/arch-hyprland
# cd arch-hyprland
# chmod +x set-hypr
# ./set-hypr

clear

echo -e "Installing Hyprland"

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then 
    echo -e "yay located, moving on."
else 
    echo -e "Yay NOT located, installing"
    git clone https://aur.archlinux.org/yay.git &>> $INSTLOG
    cd yay
    makepkg -si --noconfirm &>> ../$INSTLOG
    cd ..
fi

### Disable wifi powersave mode ###
LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC &>> $INSTLOG
echo -e "$CNT - Restarting NetworkManager service..."

sudo systemctl restart NetworkManager &>> $INSTLOG


# Installing the packages
echo -e "Updating yay database..."
yay -Suy --noconfirm 
    
echo -e "Installing main components"
yay -S --noconfirm hyprland kitty waybar swww swaylock-effects wofi wlogout mako xdg-desktop-portal-hyprland swappy grim slurp thunar

echo -e "Installing additional tools and utilities"
yay -S --noconfirm polkit-gnome python-requests pamixer pavucontrol brightnessctl bluez bluez-utils blueman network-manager-applet gvfs thunar-archive-plugin file-roller btop pacman-contrib

echo -e "Installing theme and visual related tools and utilities"
yay -S --noconfirm starship ttf-jetbrains-mono-nerd noto-fonts-emoji lxappearance xfce4-settings sddm-git qt5-svg qt5-quickcontrols2 qt5-graphicaleffects

# Start the bluetooth service
echo -e "Starting the Bluetooth Service..."
sudo systemctl enable --now bluetooth.service &>> $INSTLOG

# Enable the sddm login manager service
echo -e "Enabling the SDDM Service..."
sudo systemctl enable sddm &>> $INSTLOG
    
# Clean out other portals
echo -e "Cleaning out conflicting xdg portals..."
yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk &>> $INSTLOG


### Copy Config Files ###
echo -e "Copying config files..."
for DIR in hypr kitty mako swaylock waybar wlogout wofi 
do 
    DIRPATH=~/.config/$DIR
    echo -e "Copying $DIR config to $DIRPATH."
    cp -R $DIR ~/.config/ &>> $INSTLOG
done

# Set some files as exacutable
echo -e "$CNT - Setting some file as executable." 
chmod +x ~/.config/hypr/scripts/bgaction
chmod +x ~/.config/hypr/scripts/xdg-portal-hyprland
chmod +x ~/.config/waybar/scripts/waybar-wttr.py
chmod +x ~/.config/waybar/scripts/baraction
chmod +x ~/.config/waybar/scripts/update-sys

# Copy the SDDM theme
echo -e "$CNT - Setting up the login screen."
sudo cp -R sdt /usr/share/sddm/themes/
sudo chown -R $USER:$USER /usr/share/sddm/themes/sdt
sudo mkdir /etc/sddm.conf.d
echo -e "[Theme]\nCurrent=sdt" | sudo tee -a /etc/sddm.conf.d/10-theme.conf &>> $INSTLOG
WLDIR=/usr/share/wayland-sessions
if [ -d "$WLDIR" ]; then
    echo -e "$WLDIR found"
else
    echo -e "$WLDIR NOT found, creating..."
    sudo mkdir $WLDIR
fi 
sudo cp extras/hyprland.desktop /usr/share/wayland-sessions/
sudo sudo sed -i 's/Exec=Hyprland/Exec=\/home\/'$USER'\/start-hypr/' /usr/share/wayland-sessions/hyprland.desktop
cp extras/start-hypr ~/

#setup the first look and feel as dark
ln -sf ~/.config/waybar/style/style-dark.css ~/.config/waybar/style.css
ln -sf ~/.config/wofi/style/style-dark.css ~/.config/wofi/style.css
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface icon-theme "Adwaita-dark"
ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper-dark.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

### Install the starship shell 
echo -e '\neval "$(starship init bash)"' >> ~/.bashrc
echo -e "copying starship config file to ~/.confg ..."
cp extras/starship.toml ~/.config/

### Script is done ###
exec sudo systemctl start sddm &>> $INSTLOG
